blank_issues_enabled: false
contact_links:
  - name: General Question / Discussion
    url: https://github.com/amyavari/iran-payment-laravel/discussions
    about: "For general discussions, questions, or help, use GitHub Discussions."
